[package]
name = "dns"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

homepage = "https://github.com/eduardobaginskicosta/domainnamesystem"
authors = ["Eduardo Baginski Costa <eduardobcosta1234@gmail.com>"]

[[bin]]
name = "dns"
path = "src/main.rs"

[dependencies]
dns_core = { path = "../core" }
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
